### ISSUE TITLE
MCEF still not closing java

### ISSUE THREAD

**Issue by LokeYourLord** [montoyo/mcef#15]
So the JCEF process in the background does still run, even though it is said to be fixed in 0.6. Problem is, it is fixed in 0.7, but 0.7 does not work with WebDisplays as of the moment. Could you make a quick, fixed 0.6 version that closed JCEF properly upon exiting Minecraft? Also, maybe a quick fix to skip Linux compiling, so that people that use Linux do not get a crash anymore. Does not have to fix the compiling, but skip it just like on Mac, as Mac users do not have any problem as far as i know, while Linux users have.

**Comment by montoyo** [comment]
Hello,
The MCEF version I'm working on is using the latest JCEF version and still keeps the java process running. I've spent too many hours trying to fix this. I even tried to add some code in the DLL that kills the process 5 seconds after Minecraft's shutdown. Doesn't solve anything. This must be a (J)CEF bug and right now I'm too busy with my studies to take a look at it; sorry :(

**Comment by Yanniclord** [comment]
Could you at least fix the Linux issue?

**Comment by montoyo** [comment]
Sure, if I get some free time :)
Again, sorry if I can't do much about this but like I said, I've been extremely busy these last days...

**Comment by Yanniclord** [comment]
Hey, its ok. At least you are honest about it, and say it like it is, not like many other devs do, do the opposite or just abandon stuff altogether.

**Comment by Yanniclord** [comment]
This log is for you, in case you want it. Its about the compilation on Linux. The last pair of lines should be what you need. https://www.dropbox.com/s/wxoltqhtrelfgur/log.pdf?dl=0

**Comment by lightning02** [comment]
The same thing happens to me :(

**Comment by ScottehBoeh** [comment]
**DISCLAIMER: I know this is an old thread, but for developers who are STILL having this issue:**

Please remember that you need to have `-Dfml.coreMods.load=net.montoyo.mcef.coremod.ShutdownPatcher` as a VM argument! Otherwise, it will not load the Shutdown Patcher and close your java instance after shutting down Minecraft.

**Comment by lumeleeopard** [comment]
how would add a VM argument?
