### ISSUE TITLE
Build System or Process for mcef

### ISSUE THREAD

**Issue by TechplexEngineer** [montoyo/mcef#16]
Greetings,

I'd like to help with linux and mac compatibility.
I'm troubled that the repo doesn't have a build script included. Is this something you can add so we, who are looking to compile MCEF, don't have to start from scratch?

Thanks!

**Comment by montoyo** [comment]
Hello,

I added the missing Gradle build configuration & wrapper for MCEF 1.12.2-0.9.

Thanks for pointing it out!
