### ISSUE TITLE
Could not spawn entity ModID: WebDisplays Entity ID 6 at.... please report to mod author

### ISSUE THREAD

**Issue by lightning02** [montoyo/mcef#17]
I encountered this error (reason why I was not able to join in a private server).
At the time of the error I was using WebDisplays-0.11 and MCEF-1.7.10-0.6.
I know there is a new version actually, I'm sure gonna use that, btw, I'm not able to reproduce the issue anymore (for now...)

![immagine](https://cloud.githubusercontent.com/assets/11884147/15258759/a2f9da76-194d-11e6-914c-6fdc6110cb40.png)

**Comment by montoyo** [comment]
Hello,

This is WebDisplays related and not MCEF. Besides, I'm dropping WebDisplays 0.11 support since I'm working on a re-write, so these kind of bugs should be solved.
