### ISSUE TITLE
Why not port to Webview (or other engine)..?

### ISSUE THREAD

**Issue by vpontin** [montoyo/mcef#19]
I'm not a expert on Java, but after seeing to this day no one was able to simply build JCEF for OS X, i'm throwing some bits here:

http://docs.oracle.com/javafx/2/webview/jfxpub-webview.htm

It seems to be native of (Oracle) Java i assume it could run in any platform. Aside it uses webkit as engine, just like Chrome/CEF.

And some topics about this subject in StackOverflow:
http://stackoverflow.com/questions/48249/is-there-a-way-to-embed-a-browser-in-java
http://stackoverflow.com/questions/2020854/embed-firefox-browser-in-java-swing
http://stackoverflow.com/questions/21219966/embedding-a-web-browser-html-engine-in-java

Another thing: in next versions (if happen) you guys could make a fork of [Minecraft Forge Installer](https://github.com/MinecraftForge/Installer) to "automate" (aka put jar libraries and dll/so natives in right (standard for minecraft) folders instead of bloat .minecraft) all the thing. I'm pretty sure this would help a lot of noob users (like me).

**Comment by montoyo** [comment]
Hello,
First of all WebView is part of the Java**FX** library, which means it is for Graphical User Interfaces and I certainly won't be able to "render" it in memory (i.e. not directly on the user's screen but in an OpenGL texture that can then be rendered in Minecraft).

Also WebView doesn't support HTML5/CSS3 as good as Chromium does, and as far as I know it doesn't support Flash at all. Even though Flash has some security issues, it is still widely used and Chromium uses some kind of sandbox which "fixes" these security problems.

So no, I won't switch to another engine :)

**Comment by spannerman79** [comment]
> and as far as I know it doesn't support Flash at all. Even though Flash has some security issues

Well more then just a few security issues. Even Adobe themselves have stopped development and support/EOL of Flash from 2017-01-31 ( [Source](https://docs.adobe.com/docs/en/aem/6-1/administer/integration/marketing-cloud/scene7/flash-eol.html) )
