### ISSUE TITLE
support for localStorage, application cache

### ISSUE THREAD

**Issue by pelikhan** [montoyo/mcef#2]
It seems that the browser always starts without any prior data. Is there a way to enable AppCache and localStorage?

**Comment by pelikhan** [comment]
settings the ``cache_path`` field on the ``CefSettings`` should be enough to enable this feature.

**Comment by montoyo** [comment]
Hello!
Thanks for your contribution, I'll add this (and a way to disable the example browser) in the 1.8 update.
