### ISSUE TITLE
MCEF Still not closing Java

### ISSUE THREAD

**Issue by sonicbrandyn** [montoyo/mcef#27]
I'd love this mod in my small private pack but I cant have it so it doesnt close java down and we all gotta go into task manager to shut it down every time since it has over 300 mods it is quite an issue, Please fix <3

**Comment by spannerman79** [comment]
The number of mods doesn't matter in this case.

Personally killing the jcf helper process isn't all hard to do.

As it seems the Dev has gone on hiatus you'll just have to deal with one simple easy inconvenience - considering the majority of 1.7 and 1.8 mods are buggy and won't be updated/fixed as most/all have moved onto 1.11+

**Comment by sonicbrandyn** [comment]
Yeah but every player has to do it and some dont even know how or will forget and it will lag their computer

**Comment by montoyo** [comment]
Hello,

Hopefully this will be fixed with MCEF 1.12.2-0.9. If this happens again, re-create the issue. Until then I'm closing this one.
