### ISSUE TITLE
Black screen 1.7.10

### ISSUE THREAD

**Issue by LISARIAT** [montoyo/mcef#29]
When my friends try use webdisplay, they can't see the screen, it's always black :/
it's working for me, i don't why it's not work for my friends...

**Comment by montoyo** [comment]
Hello,
Are they using Windows? Which Minecraft launcher are they using?

**Comment by LISARIAT** [comment]
Ben déjà je remarque que tu es français aussi ^^

Ben en fait, moi le mod marche parfaitement pour moi, je me suis regardé
quelque vidéos sur internet,  sur le serveur, sa marche aussi, donc j'ai
créer un pack mod en .zip pour mes amis, j'ai mis le mod webdisplay, MCEF
et computercraft dans le dossier mod, le dossier config avec le fichier
config du webdisplay (car le serveur change l'id de l'entité de l'écran
donc il faut avoir le même que celui du serveur)

Quand mes amis installe le mod comme je leur est dis de faire, le jeu
marche, mais quand ils allument l'écran rien se passe, moi je peux voir
mais eux non, et ils ont pas le son aussi, et pareil en solo, ils ont le
même bug
Ah aussi , on a changer plusieurs fois de lien, youtube, google, etc...

Ils ont windows 10 et ils utilisent le dernier launcher sorti comme moi
Donc je sais plus quoi faire, j'ai chercher partout sur internet
"webdisplay black screen" ou bien "webdisplay 1.7.10 not work"

Le pire c'est qu'il y a pas d'erreur quand il font clique droit sur
l'écran, il n'y a que:
[16:45:07] [Client thread/INFO]: Creating webview!
Mais il ne vois rien

​Donc désolé de vous déranger pour ce soucis

Cordialement

**Comment by montoyo** [comment]
Essaye avec le vieux launcher https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.exe

**Comment by LISARIAT** [comment]
Merci
Je vais tester si c'est ça ;)

**Comment by LISARIAT** [comment]
Avez-vous une version 32bit ?

**Comment by montoyo** [comment]
Du launcher ?

**Comment by LISARIAT** [comment]
Oui, car quand il le lance il se passe rien mais moi oui je vois le launcher, et j'ai remarquer qu'il utilise un os de 32bit
Sinon si c'est pas ça je sais pas pourquoi sa ne fonctione pas le launcher que vous m'avez donné...

**Comment by montoyo** [comment]
C'est un launcher officiel de Minecraft: il devrait fonctionner dans tous les cas (sauf si java n'est pas installé bien sûr). Si il n'arrive à jouer qu'avec le nouveau launcher, je suggère de passer à Minecraft 1.10.2 ou 1.12.2. MCEF fonctionne comme il faut dans ce là, et en plus WebDisplays a bien évolué.

**Comment by LISARIAT** [comment]
Bon ben c'est c'est le launcher le problème, je vais essayer comme je peux
de le lancer...
Je vous dirais si j'arrive ^^

Le 22 février 2018 à 17:09, Nicolas Barbotin <notifications@github.com> a
écrit :

**Comment by LISARIAT** [comment]
Oui, car quand il le lance il se passe rien mais moi oui je vois le launcher, et j'ai remarquer qu'il utilise un os de 32bit
Sinon si c'est pas ça je sais pas pourquoi sa ne fonctione pas le launcher que vous m'avez donné...
