### ISSUE TITLE
(noob) better instructions on developing mod with mcef

### ISSUE THREAD

**Issue by pelikhan** [montoyo/mcef#3]
Would you mind adding more details about developing a mod with mcef? When adding the MCEF .jar file to the /eclipse/mods, the Minecraft client fails during the loading of the MCEF package (which seems to be a versioning issue).

To get it working, I end up having to run ``gradlew build`` then copy the my compiled mod into the non-dev Minecraft Forge mods folder.

**Comment by montoyo** [comment]
Oh... right I tried and I'm having the same problem. I thought Forge was able to load obfuscated mods in a deobfuscated environment, but obviously it can't :S sorry about that.
In the meantime, I think the best way is to clone the MCEF repository in your workspace. I'll write a tutorial asap.
Thanks!
