### ISSUE TITLE
Question on platforms: Building for MAc

### ISSUE THREAD

**Issue by rhysperry111** [montoyo/mcef#34]
I have all the relevant applications to build for mac, but my problem is i am using this in a modpack. If i were to compile it for mac would it still work on windows? Would it be possible to put windows AND mac builds in my mod folder?

**Comment by montoyo** [comment]
MCEF downloads its platform-specific resources from the MCEF website. So yes, kind of. The thing is JCEF is really buggy and it probably won't be as "plug & play" as you think... that's why I've never managed to get it working on Linux...
