### ISSUE TITLE
[1.7.10-0.6] Russian cyrillic symbols not supported

### ISSUE THREAD

**Issue by stepan14041999** [montoyo/mcef#36]
I can't print russian symbols into gui

**Comment by montoyo** [comment]
Perfect exemple URL @steinm07 🤣
Also @stepan14041999 did it fix your problem?

**Comment by stepan14041999** [comment]
Hi, it's uncomfortable using a additional tool for URL translating. We creating player-oriented server and what we can say to players? Use other site and copy-paste? May be, but i and many other peoples prefer useful integrated solution - working unicode support. 

P.S. Sorry my bad english, plz

**Comment by montoyo** [comment]
Will add something for this. Thanks.

**Comment by stepan14041999** [comment]
Thanks you. We will wait it with love <3

**Comment by montoyo** [comment]
Okay. This should be available in the next release.
