### ISSUE TITLE
Question on mod port to curse forge

### ISSUE THREAD

**Issue by kohlth** [montoyo/mcef#38]
hello there, as a fan of your mod web screens and of this mod, i would love to use it more

the problem is that this pack isn't on curse forge
https://minecraft.curseforge.com/

i cant really use your mod much in packs i make/share because of the fact being that 90% of mods, mod-packs and mod-pack players use the curse (also named twitch launcher after twitch merged with curse) launcher to host their mod/ play on. 

If possible i would love a port to curse and if there is a reason preventing you from doing so, i would like to know

with much hope for this mods future, kohlth

**Comment by spannerman79** [comment]
Read https://authors.curseforge.com/knowledge-base/minecraft/120-minecraft-modpack-submission and scroll down to **Third Party Mods**

**Comment by spannerman79** [comment]
> i cant really use your mod much in packs i make/share because of the fact being that 90% of mods, mod-packs and mod-pack players use the curse (also named twitch launcher after twitch merged with curse) launcher to host their mod/ play on.

I can tell you now that is a load of rubbish, there are many people moving away from the Twat Launcher to MultiMC or making a fork of SKCraft's Launcher

**Comment by kohlth** [comment]
one other question i ask is because i currently host a server for free but i can only get mods from curseforge for the server

also why are people always so salty about curse/twitch, i can understand maybe it can be a bit funny at times but its not like its the absolute worst

**Comment by spannerman79** [comment]
> one other question i ask is because i currently host a server for free but i can only get mods from curseforge for the server

That is your choice.  Every VPS I've had I have always had SSH access to.


> also why are people always so salty about curse/twitch, i can understand maybe it can be a bit funny at times but its not like its the absolute worst

Seriously?  I suggest you drop into the MultiMC discord and have a read of the horror stories that people have had with the Twat launcher and how they switched to MultiMC was **a lot** simplier and easier then what they first initially though.

Not only that the new Twat Launcher constantly comes up stating "You have no instances, click..." blah blah blah all the damn time.  And I am not the only one that has that issue.

This is starting to get off topic to the nature of this issue tracker.
The point is that for modpacks on curseforge Webdisplays etc is allowed already as a third party mod.

**Comment by montoyo** [comment]
I'm not a fan of curseforge and more importantly, I don't really like the Twitch launcher as it is built on top of Electron.

This basically means that Twitch don't want to pay real developers and instead chose to employ some cheap Javascript developers. The consequence of this is that you get a slow, buggy, and RAM-eating app and companies need to stop this shit right now. It may be cheap but it's eating of all of my goddamn RAM.

So nope, I won't port any of my mods to curseforge... sorry.
