### ISSUE TITLE
Watch videos in another platform beyond youtube in minecraft [HELP]

### ISSUE THREAD

**Issue by vini290** [montoyo/mcef#39]
I've downloaded and installed Web Displays on my minecraft and everything works fine except by one thing... if I try to watch a video from any website which isn't youtube, the video is not supported( for example: I've tried to watch netflix with my friends and I can't, vimeo also don't work). I've notice that JCEF doesn't support some codecs and I think that's why this is happening.

Could anybody help me with that? The main reason I'm posting this is because I want to watch netflix in minecraft. Does somebody have a hint? What should I do? I do appreciate any help.

**Comment by spannerman79** [comment]
Short answer: No because of Netflix DRM
Long answer: MCEF cannot have plugins https://arcolinux.com/how-to-play-netflix-in-your-chromium-browser/

**Comment by vini290** [comment]
so, is it possible to install google chrome instead of chromium in Web Displays mod?

**Comment by spannerman79** [comment]
How does my reply being 'Short answer: No because of Netflix DRM & cookie session auth' translate to being a maybe??

**Comment by montoyo** [comment]
@spannerman79 is right. Netflix uses DRM and this cannot be used with MCEF. And nope, I can't "install google chrome instead of chromium" for many reasons, including:

- Google Chrome is closed source
- There are no "library" version of Google Chrome that I can embed in Minecraft
