### ISSUE TITLE
Can't play MP4 videos

### ISSUE THREAD

**Issue by ItsK1tty** [montoyo/mcef#41]
Hey, I've tried watching Interstellar with friends, but when I'm heading to my webserver with .mp4 onboard, the screen stays white, and theres no sound or videos
Steps to reproduce:
1.Make a screen
2.Go to http://minecraft.itsk1tty.me/Interstellar.mp4 (it's russian)
3.Try to watch it.
Also, it's 1.12.2, mcef is 0.9, wd is 1.0
there's no crash, so there's no crashlogs

**Comment by montoyo** [comment]
I get a 404

**Comment by ItsK1tty** [comment]
@montoyo it's been almost a month. I've deleted this .mp4
