### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by lumeleeopard** [montoyo/mcef#42]
I added the vm argument but now it wont run the game period. It says 
Error: Could not create the java virtual machine
Error: A fatal exception has occurred. Program will exit

**Comment by montoyo** [comment]
Which VM argument? Java 32 ou 64 bits?
Usually this happens if you allocate too much/not enough RAM to Java... Also, keep in mind that Java 32 bits can only go up to 1 GiB of RAM.
