### ISSUE TITLE
Whats the new version of mcef

### ISSUE THREAD

**Issue by DatGayNekoBoy** [montoyo/mcef#43]
Is 1.1 the updated version or 1.0?

**Comment by montoyo** [comment]
1.11; there is no 1.0 version

**Comment by DatGayNekoBoy** [comment]
I meant 0.9 for mcef and 1.0 for website displays mod

**Comment by montoyo** [comment]
Just take the latest version for both; so: MCEF 1.11 and WebDisplays 1.1 👌

**Comment by DatGayNekoBoy** [comment]
Well thanks for clarifying that for me!
