### ISSUE TITLE
Game stuck when initializing

### ISSUE THREAD

**Issue by RisingInIris2017** [montoyo/mcef#50]
Mod version:
WebDisplay 1.1, MCEF 1.11
Forge version: 1.12.2-forge1.12.2-14.23.5.2838
Singleplayer or Multiplayer: Singleplayer
Description:
When I start game, it will be initialized normally, but stops when it tries to load some textures.
Here's a part log:
[23:25:53] [Client thread/INFO] [MCEF]: Now initializing MCEF v1.11...
[23:25:53] [Client thread/INFO] [MCEF]: Selected mirror: montoyo.net (over HTTPS)
[23:25:58] [Client thread/INFO] [MCEF]: Detected platform: win64
[23:25:58] [Client thread/INFO] [MCEF]: Checking for missing resources...
[23:25:58] [Client thread/INFO] [MCEF]: Found 15 missing resources. Downloading...
and logging stops at here.
Here's a link to the full log: https://paste.ubuntu.com/p/qrCN22FNhC/
Looking forward to your kindhearted help.

**Comment by spannerman79** [comment]
Not related to this issue tracker

```
Description: Failed to receive data from URL: https://gist.githubusercontent.com/gegy1000/7a6d39cf7a2c1f794ffb9037e8146adc/raw/llibrary_patrons.json

java.net.ConnectException: Connection refused: connect
    at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
```

Look at the github user ID - `gegy1000` and look at the user ID of this repo - `montoyo`

Not a webdisplay nor a MCEF issue.

**Comment by RisingInIris2017** [comment]
Thanks for your help!
Problem has been solved. It was because the LLibrary mod, made by gegy1000, tried to update something about Patreon, but failed, and then game was stuck.
Thanks again!

**Comment by RisingInIris2017** [comment]
I have got another player's latest.log, he also said his game stuck when initializing. 
https://paste.ubuntu.com/p/GnTjfVPsNF/
I used Find&Replace tool to search strings "gegy1000" and "patr" but found nothing.
I think this time the problem is not caused by LLibrary.
Looking forward your kindhearted help.

**Comment by spannerman79** [comment]
```
 java.io.FileNotFoundException: C:\Users\Ｋｕｒｉｓｕ９３\Desktop\天蝎七号的地球实验室\.minecraft\config\mcefFiles.lst (系统找不到指定的文件。)
```

For the love of **GOD** when will people stop using non ANSI characters in their username on windows...

Line 1438 of that paste. Java on windows **does not handle unicode in paths**.  That path contains unicode.

@RisingInIris2017 - next time - take the time to learn to read logs.  You'd be surprised at how _easily_ with some time and care you'd be able to track down something as simple as this.
