### ISSUE TITLE
Is HTML5 supported because YouTube streams don't work nor do Twitch streams

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [montoyo/mcef#51]
I get the #4000 error on Twitch when trying to watch a livestream and I get an unsupported error on YouTube.

**Comment by spannerman79** [comment]
goto http://html5test.com/ in WebDisplays save and share the result URL

**Comment by AdovinOFFICIAL** [comment]
Didn't mean to re-open, closing for now since I uninstalled the mod due to streams not being playable, and I can't test the html5test.com so I'm gonna close it.

**Comment by spannerman79** [comment]
So let me get this right - you created an issue, and couldn't have the paitence long enough expecting an **immediate** reply, removed the mod and at the same time kept this issue opened expecting others to read your mind??

**Comment by AdovinOFFICIAL** [comment]
nope it was because you made your reply at the same time it was uninstalled, i came to the page to close the issue and saw your reply and thought "well shit" its a big modpack that takes like 10 minutes to load up. and i didnt want to make my friends close their minecraft once again and reinstall it so we can figure out what is wrong with it
