### ISSUE TITLE
 How to update Google's version for-> 1.7.10

### ISSUE THREAD

**Issue by nnn950711** [montoyo/mcef#52]
How do I update the browser version of 1.7.10 ?

I can't watch the broadcast.

**Comment by spannerman79** [comment]
>I can't watch the broadcast.

What boradcast?

We aren't mind readers....

**Comment by nnn950711** [comment]
I can't watch the news, he will ask me to update my browser.

**Comment by spannerman79** [comment]
Unless your more specific I'm going to say Duplicate of https://github.com/montoyo/mcef/issues/39#issuecomment-482915851

**Comment by nnn950711** [comment]
Sorry my english is not very good.

Simply put: He says my browser is an old version, which makes it impossible for me to watch some content.

Html5 is not supported in legacy versions.

**Comment by montoyo** [comment]
Yeah well... updating Chromium takes a lot of time, which I don't have. Anyway, 1.7.10 is quite old now, so I'm sorry but I won't fix.
