### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by WhatTheHecht** [montoyo/mcef#62]
Hi, I installed this on my private MC server, and when I go on youtube, it shows one thing for me, and another for my friend. What can I do about this?

**Comment by Juestan** [comment]
Nothing, mcef uses the player connection to the internet not the server, thats the problem.

**Comment by montoyo** [comment]
This should be on the WebDisplays repo, but anyway... JeysRT is correct. For more info, read https://montoyo.net/wdwiki/index.php?title=Screen#Multiplayer_synchronization

This is a limit of WebDisplays and will always stay this way. Potential "fixes" for this issue would result into serious security issues or performance issues.
