### ISSUE TITLE
White screen on Windows and MCEF updated

### ISSUE THREAD

**Issue by DBPT210** [montoyo/mcef#75]
I have Windows 10 and MCEF-12.2-1.31
For some reason it has a white screen both one singleplayer and multiplayer server.

Wheres a video: https://imgur.com/a/WLOWl14
[client latest.log](https://github.com/montoyo/mcef/files/7139480/latest.log)
[server latest.log](https://github.com/montoyo/mcef/files/7139492/latest.log)

**Comment by Nlk29** [comment]
I found a soultion.
just use webdisplays vesion 1.0 and mcef version 0.9 and it should work. ;)

**Comment by DBPT210** [comment]
> I found a soultion.
> just use webdisplays vesion 1.0 and mcef version 0.9 and it should work. ;)

It worked! Thank you so much!
:)
