### ISSUE TITLE
I am a novice developer, please help me clear my doubts

### ISSUE THREAD

**Issue by GaoXanSheng** [montoyo/mcef#77]
I created a guicontainer extensions net.minecraft.client.gui.inventory.guicontainer

Then initialize the API call in drawguicontainerforegroundlayer

API api = MCEFApi.getAPI();

I used createbrowser()

And use draw () to try to display the browser. He didn't respond

I am a novice developer, please help me clear my doubts

**Comment by ItsK1tty** [comment]
This mod is abandoned by the developer. If you still need help, reach out to me on Discord: K1tty#2077
