### ISSUE TITLE
CEF Proprietary codec support

### ISSUE THREAD

**Issue by vpontin** [montoyo/mcef#9]
Hi all!
I've posted this tip on forums, but i feel better to report here, due to being the mod repository.

Well, with the current compiling way, CEF (core component of JCEF) dont support mp3 and similar formats.

BUT it can be enabled.

Some links here:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10741
http://stackoverflow.com/questions/8033495/chromium-embedded-framework-mp3-support
https://code.google.com/p/chromiumembedded/issues/detail?id=371
https://code.google.com/p/cefpython/wiki/AudioVideo

Sadly, my brain wont work with java, so the best i can help is providing this links. Sorry for the annoiyance and thanks for this awesome API!

**Comment by vpontin** [comment]
In order to use proprietary audio and video codecs in Chromium/CEF you need to:

1. Acquire ffmpeg libraries that support the proprietary codecs.
2. Add 'proprietary_codecs': 1 to your cef.gypi configuration so that USE_PROPRIETARY_CODECS will be defined as required by net/base/mime_util.cc.

**Comment by JordekFluffball** [comment]
I believe using the MP3 codec legally requires licensing. That said, I think it's either legal or ignored if it is used in small free software like this.

Compiling CEF is no easy feat. Montoyo gave up and used a precompiled CEF. I managed to compile CEf for Mac, so I may try to add the MP3 codec at some point.

Thanks for the links!

**Comment by vpontin** [comment]
I dont know, but this link https://www.ffmpeg.org/legal.html can shed light...

**Comment by montoyo** [comment]
Thanks for the links @vpontin :D
However, I don't know anything about the legal stuff behind MP3 patents etc... and there are many alternatives to MP3.
Also my download speed is 400 KiB/s, so downloading CEF, takes A LOT of time. (And then you have to compile it, so it's even worse).
Ah and let's not forget that I'll need to do it for every JCEF versions, on every OS (this means that @JordekFluffball will also have to recompile all his CEF for Mac, just to enable MP3)

**Comment by vpontin** [comment]
Sad.
A lot of webradios use mp3 (or wrost: mp4/aac) format to deliver your content. OGG isn't a widespread format to anything (except opensource/free initiatives, like Wikipedia).
About license, i remember another mods using mp3 (and even aac) freely (e.g Dragon's webradio http://www.curse.com/mc-mods/Minecraft/dragons-radio-mod). Maybe talking with this mod author can help you in clarify.
In fact, use of mp3-involved patents are (like much of minecraft related modding (eg. Bukkit)) a "gray area". See http://ffmpeg.gusari.org/viewtopic.php?f=16&t=775

I respect your fears about this case, this is a strange situation. But anyway this is sad. Much of the web runs mp3 using html5 audio tag, and this absence weights a lot.
